#!/usr/bin/env python3
"""
Cross-platform one-shot deploy runner for NL gateway stack.
Works on Linux/macOS/Windows (where Python 3 is available).
"""

from __future__ import annotations

import importlib
import os
import re
import shlex
import subprocess
import sys
import time
from dataclasses import dataclass
from getpass import getpass
from pathlib import Path
from typing import Dict, Tuple


SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_ENV_PATH = SCRIPT_DIR / ".env"
REMOTE_SCRIPT_LOCAL_PATH = SCRIPT_DIR / "scripts" / "rebuild_nl_gateway.sh"

ENV_KEYS_FOR_SAVE = [
    "SSH_HOST",
    "SSH_PORT",
    "SSH_USER",
    "SSH_PASSWORD",
    "SSH_PRIVATE_KEY",
    "SSH_KEY_PASSPHRASE",
    "SUDO_PASSWORD",
    "AUTO_INSTALL_PARAMIKO",
    "REMOTE_SCRIPT_PATH",
    "LOCAL_ARTIFACTS_DIR",
    "VLESS_UUID",
    "REALITY_SNI",
    "REALITY_DEST",
    "REALITY_PRIVATE_KEY",
    "REALITY_SHORT_ID",
    "HY2_SNI",
    "HY2_PASSWORD",
    "MTPROXY_TLS_DOMAIN",
    "MTPROXY_SECRET",
    "SKIP_PREFLIGHT_BACKUP",
    "RESTIC_REPOSITORY",
    "RESTIC_PASSWORD",
    "BORG_REPO",
    "BORG_PASSPHRASE",
]

PLACEHOLDER_VALUES = {
    "your_ssh_password",
    "your.server.ip",
    "your-server-ip",
    "example.com",
    "changeme",
    "change_me",
}


class UI:
    RESET = "\033[0m"
    BOLD = "\033[1m"
    BLUE = "\033[34m"
    GREEN = "\033[32m"
    YELLOW = "\033[33m"
    RED = "\033[31m"

    @staticmethod
    def _colorize(text: str, color: str) -> str:
        if not sys.stdout.isatty():
            return text
        return f"{color}{text}{UI.RESET}"

    @staticmethod
    def header(title: str):
        print(UI._colorize(f"\n=== {title} ===", UI.BOLD + UI.BLUE))

    @staticmethod
    def step(index: int, total: int, text: str):
        print(UI._colorize(f"\n[{index}/{total}] {text}", UI.BOLD + UI.BLUE))

    @staticmethod
    def info(text: str):
        print(UI._colorize(f"[info] {text}", UI.BLUE))

    @staticmethod
    def ok(text: str):
        print(UI._colorize(f"[ok] {text}", UI.GREEN))

    @staticmethod
    def warn(text: str):
        print(UI._colorize(f"[warn] {text}", UI.YELLOW))

    @staticmethod
    def err(text: str):
        print(UI._colorize(f"[error] {text}", UI.RED))


def parse_dotenv(path: Path) -> Dict[str, str]:
    data: Dict[str, str] = {}
    if not path.exists():
        return data

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue

        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()

        if value and value[0] in ('"', "'") and value[-1] == value[0]:
            value = value[1:-1]

        data[key] = value

    return data


def write_dotenv(path: Path, config: Dict[str, str]):
    lines = [
        "# Generated by deploy.py",
        "# You can edit values manually.",
        "",
    ]

    for key in ENV_KEYS_FOR_SAVE:
        value = config.get(key, "")
        lines.append(f"{key}={value}")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def env_get(config: Dict[str, str], key: str, default: str = "") -> str:
    return os.environ.get(key, config.get(key, default))


def as_bool(value: str, default: bool = False) -> bool:
    if not value:
        return default
    return value.strip().lower() in {"1", "true", "yes", "y", "on"}


def prompt_text(label: str, default: str = "", secret: bool = False, allow_empty: bool = False) -> str:
    while True:
        suffix = f" [{default}]" if default else ""
        if secret:
            value = getpass(f"{label}{suffix}: ")
        else:
            value = input(f"{label}{suffix}: ").strip()

        if not value and default:
            return default
        if value:
            return value
        if allow_empty:
            return ""
        UI.warn("Value cannot be empty.")


def is_placeholder(value: str) -> bool:
    cleaned = value.strip().lower()
    if not cleaned:
        return True
    if cleaned in PLACEHOLDER_VALUES:
        return True
    if "your_" in cleaned or "your." in cleaned:
        return True
    return False


def ensure_interactive_config(config: Dict[str, str], env_path: Path):
    prompted = False
    interactive = sys.stdin.isatty()

    def need(key: str, default: str = "", secret: bool = False, allow_empty: bool = False):
        nonlocal prompted
        if config.get(key) and not is_placeholder(config.get(key, "")):
            return
        if not interactive:
            raise ValueError(f"{key} is required and no interactive TTY is available")
        prompted = True
        config[key] = prompt_text(key, default=default, secret=secret, allow_empty=allow_empty)

    need("SSH_HOST")
    need("SSH_PORT", default="22")
    need("SSH_USER", default="root")

    has_password = config.get("SSH_PASSWORD") and not is_placeholder(config.get("SSH_PASSWORD", ""))
    has_key = config.get("SSH_PRIVATE_KEY") and not is_placeholder(config.get("SSH_PRIVATE_KEY", ""))

    if not has_password and not has_key:
        if not interactive:
            raise ValueError("Set SSH_PASSWORD or SSH_PRIVATE_KEY")
        prompted = True
        method = prompt_text("Auth method (password/key)", default="password")
        if method.lower().startswith("k"):
            config["SSH_PRIVATE_KEY"] = prompt_text("SSH_PRIVATE_KEY")
            config["SSH_KEY_PASSPHRASE"] = prompt_text("SSH_KEY_PASSPHRASE", secret=True, allow_empty=True)
        else:
            config["SSH_PASSWORD"] = prompt_text("SSH_PASSWORD", secret=True)

    if config.get("SSH_USER", "root") != "root" and not config.get("SUDO_PASSWORD"):
        if interactive:
            prompted = True
            config["SUDO_PASSWORD"] = prompt_text("SUDO_PASSWORD (optional)", secret=True, allow_empty=True)

    if not config.get("AUTO_INSTALL_PARAMIKO"):
        config["AUTO_INSTALL_PARAMIKO"] = "1"
    if not config.get("REMOTE_SCRIPT_PATH"):
        config["REMOTE_SCRIPT_PATH"] = "/tmp/rebuild_nl_gateway.sh"
    if not config.get("LOCAL_ARTIFACTS_DIR"):
        config["LOCAL_ARTIFACTS_DIR"] = "./artifacts"

    if prompted and interactive:
        save_choice = prompt_text("Save entered values to .env? (y/N)", default="n", allow_empty=True).lower()
        if save_choice in {"y", "yes"}:
            write_dotenv(env_path, config)
            UI.ok(f"Saved config to {env_path}")


def ensure_paramiko(auto_install: bool):
    try:
        return importlib.import_module("paramiko")
    except ImportError:
        if not auto_install:
            raise

        UI.info("paramiko not found, installing automatically...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", "paramiko"])
        return importlib.import_module("paramiko")


@dataclass
class SSHConfig:
    host: str
    port: int
    user: str
    password: str
    key_path: str
    key_passphrase: str
    sudo_password: str


def build_ssh_config(config: Dict[str, str]) -> SSHConfig:
    host = env_get(config, "SSH_HOST")
    if not host:
        raise ValueError("SSH_HOST is required")

    port = int(env_get(config, "SSH_PORT", "22"))
    user = env_get(config, "SSH_USER", "root")
    password = env_get(config, "SSH_PASSWORD")
    key_path = env_get(config, "SSH_PRIVATE_KEY")
    key_passphrase = env_get(config, "SSH_KEY_PASSPHRASE")
    sudo_password = env_get(config, "SUDO_PASSWORD")

    if not password and not key_path:
        raise ValueError("Set SSH_PASSWORD or SSH_PRIVATE_KEY")

    return SSHConfig(
        host=host,
        port=port,
        user=user,
        password=password,
        key_path=key_path,
        key_passphrase=key_passphrase,
        sudo_password=sudo_password,
    )


def connect_ssh(paramiko, cfg: SSHConfig):
    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())

    kwargs = {
        "hostname": cfg.host,
        "port": cfg.port,
        "username": cfg.user,
        "timeout": 20,
        "banner_timeout": 20,
        "auth_timeout": 20,
    }

    if cfg.key_path:
        kwargs["key_filename"] = cfg.key_path
        if cfg.key_passphrase:
            kwargs["passphrase"] = cfg.key_passphrase
        if cfg.password:
            kwargs["password"] = cfg.password
    else:
        kwargs["password"] = cfg.password

    client.connect(**kwargs)
    return client


def run_streaming(client, command: str) -> Tuple[int, str]:
    transport = client.get_transport()
    if transport is None:
        raise RuntimeError("SSH transport is not available")

    chan = transport.open_session()
    chan.get_pty()
    chan.exec_command(command)

    combined: list[str] = []

    while True:
        had_data = False

        while chan.recv_ready():
            data = chan.recv(4096).decode("utf-8", errors="replace")
            print(data, end="", flush=True)
            combined.append(data)
            had_data = True

        while chan.recv_stderr_ready():
            data = chan.recv_stderr(4096).decode("utf-8", errors="replace")
            print(data, end="", flush=True)
            combined.append(data)
            had_data = True

        if chan.exit_status_ready() and not chan.recv_ready() and not chan.recv_stderr_ready():
            break

        if not had_data:
            time.sleep(0.1)

    status = chan.recv_exit_status()
    return status, "".join(combined)


def remote_env_exports(config: Dict[str, str]) -> str:
    keys = [
        "VLESS_UUID",
        "REALITY_SNI",
        "REALITY_DEST",
        "REALITY_PRIVATE_KEY",
        "REALITY_SHORT_ID",
        "HY2_SNI",
        "HY2_PASSWORD",
        "MTPROXY_TLS_DOMAIN",
        "MTPROXY_SECRET",
        "SKIP_PREFLIGHT_BACKUP",
        "RESTIC_REPOSITORY",
        "RESTIC_PASSWORD",
        "BORG_REPO",
        "BORG_PASSPHRASE",
    ]

    parts = []
    for key in keys:
        value = env_get(config, key)
        if value:
            parts.append(f"{key}={shlex.quote(value)}")

    return " ".join(parts)


def download_summary_if_any(client, output: str, host: str, artifacts_dir: Path) -> Path | None:
    match = re.search(r"Summary saved to:\s*(/\S+)", output)
    if not match:
        return None

    remote_file = match.group(1)
    artifacts_dir.mkdir(parents=True, exist_ok=True)

    local_name = f"{host}-{Path(remote_file).name}"
    local_path = artifacts_dir / local_name

    sftp = client.open_sftp()
    try:
        sftp.get(remote_file, str(local_path))
    finally:
        sftp.close()

    return local_path


def main() -> int:
    total_steps = 7
    step = 0

    UI.header("Nebula Gateway OneClick")

    step += 1
    UI.step(step, total_steps, "Loading config")
    env_path = Path(os.environ.get("ENV_FILE", str(DEFAULT_ENV_PATH))).resolve()
    config = parse_dotenv(env_path)
    ensure_interactive_config(config, env_path)
    UI.ok(f"Using config file: {env_path}")

    step += 1
    UI.step(step, total_steps, "Checking local dependencies")
    auto_install = as_bool(env_get(config, "AUTO_INSTALL_PARAMIKO", "1"), default=True)
    paramiko = ensure_paramiko(auto_install)
    UI.ok("paramiko is ready")

    step += 1
    UI.step(step, total_steps, "Validating SSH config")
    ssh_cfg = build_ssh_config(config)
    if not REMOTE_SCRIPT_LOCAL_PATH.exists():
        raise FileNotFoundError(f"Remote script not found: {REMOTE_SCRIPT_LOCAL_PATH}")
    remote_script_path = env_get(config, "REMOTE_SCRIPT_PATH", "/tmp/rebuild_nl_gateway.sh")
    artifacts_dir = Path(env_get(config, "LOCAL_ARTIFACTS_DIR", str(SCRIPT_DIR / "artifacts"))).resolve()
    UI.ok(f"Target: {ssh_cfg.user}@{ssh_cfg.host}:{ssh_cfg.port}")

    step += 1
    UI.step(step, total_steps, "Connecting to server")
    client = connect_ssh(paramiko, ssh_cfg)
    UI.ok("SSH connection established")

    try:
        step += 1
        UI.step(step, total_steps, "Uploading bootstrap script")
        sftp = client.open_sftp()
        try:
            sftp.put(str(REMOTE_SCRIPT_LOCAL_PATH), remote_script_path)
        finally:
            sftp.close()
        run_streaming(client, f"chmod +x {shlex.quote(remote_script_path)}")
        UI.ok(f"Uploaded to {remote_script_path}")

        step += 1
        UI.step(step, total_steps, "Executing remote provisioning")
        exports = remote_env_exports(config)
        exports_prefix = f"{exports} " if exports else ""

        if ssh_cfg.user == "root":
            remote_cmd = f"set -euo pipefail; {exports_prefix}bash {shlex.quote(remote_script_path)}"
        else:
            if ssh_cfg.sudo_password:
                remote_cmd = (
                    "set -euo pipefail; "
                    f"{exports_prefix}echo {shlex.quote(ssh_cfg.sudo_password)} | "
                    f"sudo -S -E bash {shlex.quote(remote_script_path)}"
                )
            else:
                remote_cmd = (
                    "set -euo pipefail; "
                    f"{exports_prefix}sudo -E bash {shlex.quote(remote_script_path)}"
                )

        code, output = run_streaming(client, remote_cmd)
        if code != 0:
            UI.err(f"Remote provisioning failed with exit code: {code}")
            return code
        UI.ok("Remote provisioning completed")

        step += 1
        UI.step(step, total_steps, "Downloading artifacts")
        local_summary = download_summary_if_any(client, output, ssh_cfg.host, artifacts_dir)
        if local_summary:
            UI.ok(f"Summary downloaded to: {local_summary}")
        else:
            UI.warn("Summary path not detected in output")

        UI.header("Done")
        UI.ok("Gateway deployment finished successfully")
        return 0
    finally:
        client.close()


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        UI.warn("Interrupted by user")
        raise SystemExit(130)
    except Exception as exc:
        UI.err(str(exc))
        raise SystemExit(1)
